# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmbedNativeDemo_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmbedNativeDemo_Swift
  # 'node_modules'目录一般位于根目录中
  # 但是如果你的结构不同，那你就要根据实际路径修改下面的`:path`
  pod 'React', :path => 'ReactNative/node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # 这个模块是用于调试功能的
    # 在这里继续添加你所需要的模块
  ]
  # 如果你的RN版本 >= 0.42.0，请加入下面这行
  pod "Yoga", :path => "ReactNative/node_modules/react-native/ReactCommon/yoga"

  target 'EmbedNativeDemo_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmbedNativeDemo_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
